services:
  web-service:
    build: web/apache
    container_name: wosec-web
    networks:
      my_network:
        ipv4_address: 172.18.0.12

  
  firewall:
    container_name: wosec-fwl
    build: web/firewall
    networks:
      my_network:
        ipv4_address: 172.18.0.23
    tty: true
    privileged: true

  ftp-server:
    container_name: wosec-ftp
    environment:
      - FTP_PASS=123
      - FTP_USER=user
    image: garethflowers/ftp-server
    volumes:
      - '/data:/home/user'
    networks:
      my_network:
        ipv4_address: 172.18.0.25


  ftpd-anon:
    container_name: wosec-ftp-anon
    build: ./web/ftp-anon/
    ports:
        - "20-21:20-21"
        - "65500-65515:65500-65515"
    volumes:
        - "/tmp:/var/ftp:ro"
    environment:
        - FTPD_BANNER=Anonymous FTP server
    networks:
      my_network:
        ipv4_address: 172.18.0.10

  db:
    image: mysql
    container_name: wosec-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
    networks:
      my_network:
        ipv4_address: 172.18.0.33

  samba:
    image: dperson/samba
    container_name: wosec-smbserver
    environment:
      TZ: 'EST5EDT'
    networks:
      my_network:
        ipv4_address: 172.18.0.38
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt:/mnt:z
      - /mnt2:/mnt2:z
    command: '-s "Mount;/mnt" -s "Bobs Volume;/mnt2;yes;no;no;bob" -u "bob;bobspasswd" -p'

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
